export interface IopTableRow {
    id: string;
    brojIOP: string,
    vrstaIOP: string,
    statusIOP: string,
    uvijeti: string,
    ugovor: string,
    statusU: string,
    naziv: string,
    vrsta: string,
}

export const MOCK = [
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    },
    {
        id: '1',
        brojIOP: 'OV-1234',
        vrstaIOP: 'zadužnica primatelja',
        statusIOP: 'arhiviran',
        uvijeti: 'DA',
        ugovor: 'DA',
        statusU: '10',
        naziv: 'naziv primjer',
        vrsta: 'vrsta primjer', 
    }
]
